# GEMINI
gemini:
  distance: mmd
  ovo: true

result_path: ./results/cifar10_resnet
data_path: /home/lohl/data

# Dataset
dataset: data/custom_datasets/cifar10.py
dataset_kwargs:
similarity_fct: data/custom_similarities/SIMCLRKernel.py
similarity_kwargs:

use_cuda: true

# Regularisation
regularisations:
  entropy_weight: 0.0
  vat_weight: 0.0
  vat_kwargs:
    xi: 10.0
    eps: 0.1
  reconstruction_weight: 0.0

# Model
model:
  encoder: models/custom_models/resnet18.py
  encoder_kwargs:
  clustering_head: models/custom_models/clustering_head_linear.py
  clustering_head_kwargs:
    num_clusters: 10
    input_shape: 1000

  

# Training
epochs: 200
optimiser: adam
learning_rate: 0.001
batch_size: 500
num_workers: 16

# Evaluation
metrics:
  ari: on
  accuracy: on
  purity: on
  used_clusters: on