# GEMINI
gemini:
  distance: hellinger
  ovo: false

result_path: ./results/mnist/lenet5/hellinger_false
data_path: /home/lohl/data

# Dataset
dataset: data/custom_datasets/mnist32.py
dataset_kwargs:
similarity_fct:
similarity_kwargs:

use_cuda: true

# Regularisation
regularisations:
  entropy_weight: 0.0
  vat_weight: 0
  vat_kwargs:
    xi: 10.0
    eps: 1.0
  reconstruction_weight: 0.0

# Model
model:
  encoder: models/custom_models/encoder_lenet5.py
  encoder_kwargs:
  clustering_head: models/custom_models/clustering_head_linear.py
  clustering_head_kwargs:
    input_shape: 84
    num_clusters: 15

  

# Training
epochs: 500
optimiser: adam
learning_rate: 0.001
batch_size: 250
num_workers: 16

# Evaluation
metrics:
  ari: on
  accuracy: on
  purity: on
  used_clusters: on